" vim: ff=unix ts=3 ss=2 tw=72 fdm=marker foldmarker={,}
colorscheme varoa
syntax on

" ASSORTED CONFS {
" let backspace past start of edit
"     autoindenting and start of line
set backspace=start,indent,eol
set colorcolumn=81
set completeopt=menu,preview " show a menu, and tips if available
set cursorline " highlight cursor line
set diffopt=vertical,filler,iwhite " options for diff mode
set encoding=utf-8
set errorformat=%m\ in\ %f\ on\ line\ %l
set expandtab
set fdm=marker
set ff=unix
set formatoptions=qrn1 " testing, before t
set hlsearch " highlight all search matches
set ignorecase
set incsearch " find while searching
set laststatus=2
set linebreak
set list
set listchars=tab:»\ ,trail:⬞,precedes:«,extends:»,nbsp:⬞
set makeprg=php\ -l\ % " check syntax on file & jump to error
set modelines=1
set mouse=a
set nocompatible
set nostartofline " make gg and G keep the column
set number
set path=** " ^wf finds the class file under cursor
set ruler
set scrolloff=3
set shiftwidth=4
set showcmd
set showmatch
set showmode
set smartcase
set smartindent
set sw=4
set tabstop=4
set tags=$PWD/tags;/.  " set tags if generated
set ttyfast " improve scrolling
" set ttymouse=xterm2 " so that the mouse works inside tmux
set tw=72
set viminfo='20,<50,s10,h,% " remember some stuff after quiting vim:
set wildignore+=target/**,*.class
set wildmenu " file/command completion with results count, allow tabbing
set wildmode=longest,full
set wrap
set wrapscan " make search go back to start of file
" }

" SYNTAX ENFORCEMENT {
au BufNewFile,BufRead *.phtml set filetype=php
au BufRead,BufNewFile *.scala set filetype=scala
au BufRead,BufNewFile *.md set filetype=markdown
filetype plugin indent on " filetype and php autocomplete. The indent is for vundle
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd Filetype java set makeprg=javac\ %
autocmd Filetype scala set makeprg=scalac\ %
" }

" MAPPINGS {
" change personal modifier key to , instead of \.
let mapleader = ","
" Get rid of ex mode by accident
nnoremap Q <nop>
" Clear highlight
nnoremap <C-h> :noh<CR>
" disable arrow keys (or make them useful)
map <up> <nop>
map <down> <ESC><C-W>w
map <left> <ESC>:tabp<CR>
map <right> <ESC>:tabn<CR>
inoremap <up> <nop>
inoremap <down> <ESC><C-W>w
inoremap <left> <ESC>:tabp<CR>
inoremap <right> <ESC>:tabn<CR>
" make - support /, one of those benefits of english keyboards
nnoremap - /
" edit and source .vimrc
nnoremap <leader>ev :vs $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>
" wrap words in things, there must be a more elegant way.
nnoremap <leader>( viw<esc>a)<esc>hbi(<esc>lel
nnoremap <leader>[ viw<esc>a]<esc>hbi[<esc>lel
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
" operator pending, inner prev/next brackets
onoremap ip( :<c-u>normal! F)vi(<cr>
onoremap in( :<c-u>normal! f(vi(<cr>
" operator pending, inner prev/next sgl quotes
onoremap ip' :<c-u>normal! F'vi'<cr>
onoremap in' :<c-u>normal! f'vi'<cr>
" operator pending, inner prev/next dbl quotes
onoremap ip" :<c-u>normal! F"vi"<cr>
onoremap in" :<c-u>normal! f"vi"<cr>
" sane j, k movements for screen line, not file
nnoremap j gj
nnoremap k gk
" comment line
nnoremap <leader>7 0i//<esc>
" comment visual area
vnoremap <leader>7 :s/^/\/\//g<cr>
" quick vertical, horizontal splits
nnoremap <leader>! :vs<cr><C-w>w
nnoremap <leader>_ :sp<cr><C-w>w
" clear trailing whitespace
" nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>
" remap control-space to autocompletion
" see http://robots.thoughtbot.com/post/27041742805/vim-you-complete-me
inoremap <Nul> <C-N>
" I need no help
inoremap <F1> <ESC>
vnoremap <F1> <ESC>
nnoremap <F1> <ESC>
" a new log entry
inoremap <c-l> <c-R>=LogEntry()<cr><esc>kkyypVr-o

func! LogEntry ()
    return strftime("%Y%m%d {{{\n}}}\n")
endfunc

" }

" REPLACEMENTS {
iab tau @author Galo Navarro <anglorvaroa@gmail.com>
" iab tnow <ESC>:r !date +%Y%m%d<CR>kJA
iab <expr> tnow strftime("%Y%m%d %H:%M:%S")
iab <expr> tdat strftime("%Y%m%d")
" }

" { VUNDLE SETUP (github.com/gmarik/vundle)
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" let Vundle manage Vundle, required
Bundle 'gmarik/vundle'
" add your bundles here
" original repos on github
Bundle 'kien/ctrlp.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'kana/vim-fakeclip'
Bundle 'airblade/vim-gitgutter.git'
" non-github repos
" Bundle 'git://git.wincent.com/command-t.git'
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of
"     unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
" }

" { CTRL-P
" see https://github.com/kien/ctrlp.vim
nnoremap ,f :CtrlP<CR>
" let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$\|\.mo$\|\.po$\|\pot$\|\.json$'
let g:ctrlp_custom_ignore = '\.\(git\|hg\|svn\|mo\|po\|pot\|json\|jar\|class\|gif\|jpg\|jpeg\|png\|bin\|css\)$'
let g:ctrlp_custom_ignore = '\.\(git\|hg\|svn\|jar\|class\|gif\|jpg\|jpeg\|png\|bin\)$'
let g:ctrlp_working_path_mode = 'r'
" }

" For Java {
" http://stackoverflow.com/questions/6411979/compiling-java-code-in-vim-more-efficiently/14727153#14727153
set errorformat=%A%f:%l:\ %m,%-Z%p^,%-C%.%#
map <F2> :make<Return>:copen<Return>
map <F3> :cprevious<Return>
map <F4> :cnext<Return>
" }
