#!/bin/bash

function single {
    xrandr --output $PRIMARY --primary --mode $PRIMARY_MODE --pos 0x0
    # turn off all other monitors (even if plugged in)
    xrandr | grep connected | grep -v "eDP" | grep -v "LVDS-1" | cut -f1 -d ' ' | while read MON ; do
        xrandr --output $MON --off
    done
    # Dunst doesn't handle the screen switch well, force restart
    killall dunst

    notify-send "Single screen $PRIMARY"
}

function dual {
    SCALE=1
    SECONDARY=$(xrandr | grep " connected" | grep -v $PRIMARY | cut -f1 -d' ')
    SECONDARY_MODE=$(xrandr | grep "$SECONDARY" -A1 | tail -n1 | xargs | cut -f1 -d' ')
    SEC_HEIGHT=$(echo $SECONDARY_MODE | cut -f2 -dx)
    SEC_HEIGHT_SCALED=$(echo "scale=0;$SEC_HEIGHT*1.7" | bc)
    xrandr --output $SECONDARY --noprimary --mode $SECONDARY_MODE --rotate normal --scale ${SCALE}x${SCALE}
    xrandr --output $PRIMARY   --primary   --mode $PRIMARY_MODE --pos 0x$(echo $SEC_HEIGHT_SCALED | cut -f1 -d.)

    # The image will be wrongly scaled in the second monitor, fix that
    feh --bg-scale ~/.i3/whaam.jpg

    notify-send "Dual screen, (1) $PRIMARY (2) $SECONDARY"
}

PRIMARY=$(xrandr | grep " connected" | grep "eDP" | cut -f1 -d' ')
if [ -z "$PRIMARY" ] ; then
    PRIMARY=$(xrandr | grep " connected" | grep "LVDS-1" | cut -f1 -d' ')
fi
if [ -z "$PRIMARY" ] ; then
    PRIMARY=$(xrandr | grep " connected" | grep "LVDS1" | cut -f1 -d' ')
fi
PRIMARY_MODE=$(xrandr | grep "$PRIMARY" -A1 | tail -n1 | xargs | cut -f1 -d' ')

if [ "$(xrandr | grep -w connected | wc -l)" -eq "2" ]; then
    dual
else
    single
fi
